application: paul-shantanu-bputapp
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /default.php
  script: default.php

- url : /notice.php
  script : notice.php

- url : /json.php
  script : json.php

- url : /exam_schedule.php
  script : exam_schedule.php

- url : /semester_options.php
  script : semester_options.php

- url : /branch_options.php
  script : branch_options.php

- url : /test.html
  static_files : test.html
  upload : test.html

- url : /example.php
  script : example.php

- url : /test_form.html
  static_files : test_form.html
  upload : test_form.html